### PR TITLE
[feat] add benchmark + some tiny chores

### PR DESCRIPTION
**Pull request by MangoIV**
- remove some unnecessary syntax
- add benchmark to check whether sequitur is indeed linear
- add some things to .gitignore

I have also got some ideas for possible performance improvements and I also have a nix setup stashed, so let me know if you'd like these upstreamed. 

measurements

### CODE REVIEW

**Comment by MangoIV** [comment]
I also wanted to implement this algorithm a while ago but I didn't find the time. What you did is pretty much what I started doing as well. It's a pity that there's no more "functional" datastructure with the same properties as the HashTable + doubly linked list combination.

**Comment by MangoIV** [comment]
I can also add the speedscope results but they're not so useful as everything inlines into `encode` and `add`, so you end up with something like this: 
image
where the little fizzles are calls to `Hashable`

**Review by msakai — APPROVED** [review]
LGTM!

**Comment by msakai** [comment]
Thank you for the PR!

> I have also got some ideas for possible performance improvements and I also have a nix setup stashed, so let me know if you'd like these upstreamed.

Of course, performance improvements are welcome.
The only improvement I can think of now is to use [PrimVar](https://hackage.haskell.org/package/primitive-0.9.0.0/docs/Data-Primitive-PrimVar.html).

I'm not a nix user and can't maintain a nix setup, but it's ok to add if you want.

> I also wanted to implement this algorithm a while ago but I didn't find the time. 

I had been the same. Then [this year's ICFP programming contest](https://icfpcontest2024.github.io/) came in. In some of its problems, data compression may improve the score. I noticed the possibility of using the sequitur algorithm. Although I did not have time to implement it during the contest, I began implementing it after the contest ended.

By the way, do you have any applications you would like to use this implementation for?

**Comment by MangoIV** [comment]
> By the way, do you have any applications you would like to use this implementation for?

in fact, I'm using it right now because I'm writing my BSc. thesis about calculating the longest common prefix of context free grammars, not only is an SLP a nice grammar to test roundtripping on, but the algorithm also crucially depends on the grammar at hand to not be expanded, i.e. the languages we look at should be present as a set of compressed strings, so maybe I will use it to improve some things there.

**Comment by MangoIV** [comment]
> The only improvement I can think of now is to use [PrimVar](https://hackage.haskell.org/package/primitive-0.9.0.0/docs/Data-Primitive-PrimVar.html).

I have some hunches but obviously, I would have to profile carefully, I'll see if I find time for this :3 

> I'm not a nix user and can't maintain a nix setup, but it's ok to add if you want.

I think if you don't use it, it doesn't make much sense, I don't want to clutter your repo with code that may go stale etc, it is fine to keep it not checked out but perhaps just be aware that I have this lying around if people are asking ;)

**Comment by msakai** [comment]
> in fact, I'm using it right now because I'm writing my BSc. thesis about calculating the longest common prefix of context free grammars, not only is an SLP a nice grammar to test roundtripping on, but the algorithm also crucially depends on the grammar at hand to not be expanded, i.e. the languages we look at should be present as a set of compressed strings, so maybe I will use it to improve some things there.

Sorry for the late reply.
This looked like an interesting project. 
I would be delighted if the code in this repository is helpful.

**Pull request merged**
